### ISSUE TITLE
issue in installing stitch2d

### ISSUE THREAD

**Issue by Abhigulve** [adamancer/stitch2d#1]
i'm getting following error in installation 

OS:- Ubantu 17.10
I also updated the supertool still no mluck
> Collecting stitch2d
  Using cached https://files.pythonhosted.org/packages/92/98/27704653b0243eebb1c08ef9e82475edda58ee841a0e768bed40e2d470fa/stitch2d-0.31.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/stitch2d.egg-info
    writing top-level names to pip-egg-info/stitch2d.egg-info/top_level.txt
    writing pip-egg-info/stitch2d.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7fo41qxe/stitch2d/setup.py", line 35, in <module>
        zip_safe=False)
      File "/home/gulve/anaconda3/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/home/gulve/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/gulve/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/gulve/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/gulve/anaconda3/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 288, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/home/gulve/anaconda3/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 613, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/home/gulve/anaconda3/lib/python3.5/distutils/dist.py", line 1107, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/home/gulve/anaconda3/lib/python3.5/site-packages/setuptools/dist.py", line 91, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/home/gulve/anaconda3/lib/python3.5/distutils/util.py", line 471, in rfc822_escape
        lines = header.split('\n')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7fo41qxe/stitch2d/

**Comment by adamancer** [comment]
Much, much too late on this but the installation issues that have dogged this package for years should be resolved now.
